name: entertainment
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ^2.2.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/dio
  dio: ^4.0.0

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.0.0

  # https://pub.dev/packages/provider
  provider: ^5.0.0

  # https://github.com/ymingt/flutter_easyloading
  flutter_easyloading: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
